# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spotti' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spotti
pod 'Parse'
pod 'AFNetworking'
pod 'Parse/UI'
pod 'AutoCompletion'

  target 'SpottiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpottiUITests' do
    # Pods for testing
  end

end
